namePrefix: rollout-
images:
- name: ellinj/spring-demo
  newTag: bluebad
commonLabels:
  app: rollout-spring-demo
resources:
- spring-demo-pod.yml
- spring-demo-service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- rollout-transform.yaml
