apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  inputs:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 15s
    successCondition: result >= 0.25
    failureLimit: 3
    prometheus:
      address: http://prometheus.example.com:9090
      query: |
        sum(irate(
          http_server_requests_seconds_count{status=~"5.*", uri="/"}[1m]
        )) / 
        sum(irate(
          http_server_requests_seconds_count{kubernetes_name="$application" , uri="/"}[1m]
        ))



