apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
  labels:
    app: spring-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: ellinj/spring-demo:0.86.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
          env:
          - name: METRICS_EXPORT_WAVEFRONT_URI
            valueFrom:
              secretKeyRef:
                name: wavefront-token
                key: wavefront-token
