apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    prometheus.io/path: '/actuator/prometheus'
  name: spring-demo-web
spec:
  selector:
    app:  spring-demo
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lb-spring-demo-web
spec:
  selector:
    app:  spring-demo
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8080
    port: 80
    protocol: TCP


